apiVersion: apps/v1
kind: Deployment
metadata:
  name: kie-wb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kie-wb
  template:
    metadata:
      labels:
        app: kie-wb
    spec:
      volumes:
      # EFS mapped directory
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      containers:
        - name: kie-wb
          image: scb-docker-registry/business-central-workbench-ha
          ports:
            - containerPort: 8080
            - containerPort: 9990
            - containerPort: 7600
            - containerPort: 8888
          securityContext:
            privileged: true
          volumeMounts:
            - name: nfs
              mountPath: "/data/niogit"
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JGROUPS_PING_PROTOCOL
              value: "dns.DNS_PING"
            - name: DNS_PING_SERVICE_NAME
              value: "kie-wb-ping-service"        
            - name: AMQ_HOST
              value: "10.232.14.192"
            - name: AMQ_USER
              value: "admin"
            - name: AMQ_PASSWORD
              value: "admin"
---
kind: Service
apiVersion: v1
metadata:
  name: kie-wb
spec:
  selector:
    app: kie-wb
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9990"
      port: 9990
      targetPort: 9990
    - name: "9993"
      port: 9993
      targetPort: 9993
    - name: "8787"
      port: 8787
      targetPort: 8787
  #type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kie-wb-np
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  selector:
    app: kie-wb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kie-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kie
  template:
    metadata:
      labels:
        app: kie
    spec:
      containers:
        - name: kie
          image: jboss/kie-server-showcase:7.54.0.Final
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          env:
            - name: KIE_WB_ENV_KIE_CONTEXT_PATH
              value: "business-central"
---
kind: Service
apiVersion: v1
metadata:
  name: kie-server
spec:
  selector:
    app: kie
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kie-server-np
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31002
  selector:
    app: kie
# type: LoadBalancer