apiVersion: v1
kind: Service
metadata:
  name: kie-wb-ping-service
  annotations:
    description: The JGroups ping service for clustering discovery.
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kie-wb